customhost = "employee-database.c6t3wgjsr0uv.us-east-1.rds.amazonaws.com"
customuser = "goroiivanov"
custompass = "Csca1948"
customdb = "employee"
custombucket = "addemployee88"
customregion = "us-east-1"